# Generated by Django 4.0.1 on 2022-03-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bean_flavours_bean_flavours'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='colour',
            field=models.CharField(default='#ffffff', max_length=6),
        ),
        migrations.AddField(
            model_name='bean',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
