# Generated by Django 4.0.1 on 2022-03-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bean_colour_bean_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='colour',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
